#pragma once
// GameNamesDb.h — 내장 게임명 데이터베이스 (헤더 전용)
// rom파일명 → 표시명 (한글/영문 혼용)

#include <QHash>
#include <QString>

inline const QHash<QString, QString>& gameNamesDb() {
    static const QHash<QString, QString> db = {
        // ── NeoGeo — KOF ──────────────────────────────────
        {"kof94",    "킹 오브 파이터즈 '94"},
        {"kof95",    "킹 오브 파이터즈 '95"},
        {"kof96",    "킹 오브 파이터즈 '96"},
        {"kof97",    "킹 오브 파이터즈 '97"},
        {"kof97k",   "킹 오브 파이터즈 '97 (Korean)"},
        {"kof98",    "킹 오브 파이터즈 '98"},
        {"kof98k",   "킹 오브 파이터즈 '98 (Korean)"},
        {"kof99",    "킹 오브 파이터즈 '99"},
        {"kof2000",  "킹 오브 파이터즈 2000"},
        {"kof2001",  "킹 오브 파이터즈 2001"},
        {"kof2002",  "킹 오브 파이터즈 2002"},
        {"kof2003",  "킹 오브 파이터즈 2003"},
        {"kof10th",  "킹 오브 파이터즈 10th Anniversary"},
        {"kof2k2um", "킹 오브 파이터즈 2002 Unlimited Match"},
        // ── NeoGeo — Metal Slug ───────────────────────────
        {"mslug",    "메탈 슬러그"},
        {"mslug2",   "메탈 슬러그 2"},
        {"mslugx",   "메탈 슬러그 X"},
        {"mslug3",   "메탈 슬러그 3"},
        {"mslug4",   "메탈 슬러그 4"},
        {"mslug5",   "메탈 슬러그 5"},
        {"mslug6",   "메탈 슬러그 6"},
        {"mslug7",   "메탈 슬러그 7"},
        // ── NeoGeo — Samurai Shodown ──────────────────────
        {"samsho",   "사무라이 스피리츠"},
        {"samsho2",  "진 사무라이 스피리츠"},
        {"samsho3",  "사무라이 스피리츠 참사로의 길"},
        {"samsho4",  "사무라이 스피리츠 4"},
        {"samsho5",  "사무라이 스피리츠 5"},
        {"samsho5s", "사무라이 스피리츠 5 Special"},
        // ── NeoGeo — Garou / Fatal Fury ───────────────────
        {"garou",    "가로우 마크 오브 더 울브스"},
        {"fatfury1", "파이널 파이트 Special"},
        {"fatfury2", "파이탈 퓨리 2"},
        {"fatfury3", "파이탈 퓨리 3"},
        {"fatfursp", "파이탈 퓨리 Special"},
        {"rbff1",    "리얼 바웃 파이탈 퓨리"},
        {"rbff2",    "리얼 바웃 파이탈 퓨리 2"},
        {"rbffspec", "리얼 바웃 파이탈 퓨리 Special"},
        // ── NeoGeo — Art of Fighting ──────────────────────
        {"aof",      "용호의 권"},
        {"aof2",     "용호의 권 2"},
        {"aof3",     "용호의 권 외전"},
        // ── NeoGeo — World Heroes ─────────────────────────
        {"worldhero","월드 히어로즈"},
        {"wh2",      "월드 히어로즈 2"},
        {"wh2j",     "월드 히어로즈 2 Jet"},
        {"whp",      "월드 히어로즈 Perfect"},
        // ── NeoGeo — Puzzle / Sports ──────────────────────
        {"pbobblen", "Puzzle Bobble"},
        {"pbobble2", "Puzzle Bobble 2"},
        {"pbobble3", "Puzzle Bobble 3"},
        {"pbobble4", "Puzzle Bobble 4"},
        {"puyopuy2", "Puyo Puyo 2"},
        {"neo-geo",  "NeoGeo BIOS"},
        // ── NeoGeo — Shooters ─────────────────────────────
        {"blazstar", "Blazing Star"},
        {"rlpinbal", "Riding Hero"},
        {"strikers", "Strikers 1945 Plus"},
        {"s1945p",   "Strikers 1945 Plus"},
        {"lastblad", "Last Blade"},
        {"lastbld2", "Last Blade 2"},
        {"zupapa",   "Zupapa!"},
        {"magdrop2", "Magical Drop 2"},
        {"magdrop3", "Magical Drop 3"},
        {"neobombe", "Neo Bomberman"},
        {"turfmast", "Neo Turf Masters"},
        {"viewpoin", "Viewpoint"},
        {"spinmast", "Spinmaster"},
        {"sengoku",  "戦国伝承"},
        {"sengoku2", "戦国伝承 2"},
        {"sengoku3", "戦国伝承 3"},
        {"rotd",     "Rage of the Dragons"},
        {"zintrick", "Andro Dunos"},
        {"androdun", "Andro Dunos"},
        // ── NeoGeo — Baseball/Soccer ──────────────────────
        {"nam1975",  "NAM-1975"},
        {"mahretsu", "Mahjong Club"},
        // ── CPS1 ─────────────────────────────────────────
        {"sf2",      "스트리트 파이터 II"},
        {"sf2ce",    "스트리트 파이터 II': CE"},
        {"sf2hf",    "스트리트 파이터 II': HF"},
        {"sf2m1",    "스트리트 파이터 II'"},
        {"sf2koryu", "스트리트 파이터 II Koryu"},
        {"mercs",    "머스크 오브 시저"},
        {"unsquad",  "Area 88"},
        {"ffight",   "파이널 파이트"},
        {"ffightu",  "파이널 파이트 (USA)"},
        {"ghouls",   "대마계촌"},
        {"ghoulsu",  "대마계촌 (USA)"},
        {"varth",    "Varth"},
        {"1941",     "1941: Counter Attack"},
        {"3wonders", "Three Wonders"},
        {"captcomm", "Captain Commando"},
        {"knights",  "Knights of the Round"},
        {"willow",   "Willow"},
        {"cawing",   "Cawing"},
        {"dynwar",   "Dynasty Wars"},
        {"strider",  "스트라이더 비룡"},
        {"forgottn", "Forgotten Worlds"},
        // ── CPS2 ─────────────────────────────────────────
        {"ssf2",     "슈퍼 스트리트 파이터 II"},
        {"ssf2t",    "슈퍼 스트리트 파이터 II Turbo"},
        {"ssf2u",    "슈퍼 스트리트 파이터 II (USA)"},
        {"ssf2xj",   "슈퍼 스트리트 파이터 II X"},
        {"xmcota",   "X-Men: Children of the Atom"},
        {"msh",      "Marvel Super Heroes"},
        {"xmvsf",    "X-Men vs. Street Fighter"},
        {"mshvsf",   "Marvel Super Heroes vs. Street Fighter"},
        {"mvsc",     "Marvel vs. Capcom"},
        {"mvc2",     "Marvel vs. Capcom 2"},
        {"vsav",     "Vampire Savior"},
        {"vhunt2",   "Vampire Hunter 2"},
        {"vsav2",    "Vampire Savior 2"},
        {"avsp",     "Alien vs. Predator"},
        {"batcir",   "Battle Circuit"},
        {"ddtod",    "Dungeons & Dragons: Tower of Doom"},
        {"ddsoma",   "Dungeons & Dragons: Shadow over Mystara"},
        {"armwar",   "Armored Warriors"},
        {"progear",  "プロギアの嵐"},
        {"19xx",     "19XX: The War Against Destiny"},
        {"1944",     "1944: The Loop Master"},
        {"csclub",   "Capcom Sports Club"},
        {"cyvern",   "Cyberbots"},
        {"cybots",   "Cyberbots: Full Metal Madness"},
        {"gigawing", "Giga Wing"},
        {"gigawing2","Giga Wing 2"},
        {"pzloop2",  "Puzz Loop 2"},
        {"mmatrix",  "Mars Matrix"},
        {"dimahoo",  "Dimahoo"},
        {"mpang",    "Magic Sword"},
        {"sfz",      "스트리트 파이터 Zero"},
        {"sfza",     "스트리트 파이터 Zero α"},
        {"sfz2",     "스트리트 파이터 Zero 2"},
        {"sfz2a",    "스트리트 파이터 Zero 2 Alpha"},
        {"sfz3",     "스트리트 파이터 Zero 3"},
        {"sfz3u",    "스트리트 파이터 Zero 3 (USA)"},
        {"sfz3t",    "스트리트 파이터 Zero 3 Upper"},
        {"sfa",      "Street Fighter Alpha"},
        {"sfa2",     "Street Fighter Alpha 2"},
        {"sfa3",     "Street Fighter Alpha 3"},
        // ── CPS3 ─────────────────────────────────────────
        {"redearth", "Red Earth"},
        {"sfiii",    "스트리트 파이터 III"},
        {"sfiii2",   "스트리트 파이터 III: 2nd Impact"},
        {"sfiii3",   "스트리트 파이터 III: 3rd Strike"},
        {"jojo",     "JoJo의 기묘한 모험"},
        {"jojoba",   "JoJo의 기묘한 모험 BA"},
        // ── Taito ─────────────────────────────────────────
        {"ddonpach", "DoDonPachi"},
        {"donpachi", "DonPachi"},
        {"esprade",  "ESP Ra.De."},
        {"ketsui",   "絆地獄たち"},
        {"dfeveron", "Dangun Feveron"},
        {"ibara",    "茨巧"},
        {"pinkswts", "Pink Sweets"},
        // ── Sega ──────────────────────────────────────────
        {"outrun",   "Out Run"},
        {"afterbur", "After Burner"},
        {"shinobi",  "Shinobi"},
        {"aliensyn", "Alien Syndrome"},
        // ── Konami ────────────────────────────────────────
        {"contra",   "Contra"},
        {"gradius",  "Gradius"},
        {"gradius2", "Gradius II"},
        {"gradius3", "Gradius III"},
        {"salamand", "Salamander"},
        {"turtles",  "Teenage Mutant Ninja Turtles"},
        {"tmnt2",    "TMNT: Turtles in Time"},
        {"simpsons", "The Simpsons"},
        // ── Namco ─────────────────────────────────────────
        {"galaga",   "갤러그"},
        {"gaplus",   "Galaga 3"},
        {"gallag",   "Galaga (bootleg)"},
        {"pacman",   "팩맨"},
        {"mspacman", "Ms. Pac-Man"},
        {"polepos",  "Pole Position"},
        // ── Various ───────────────────────────────────────
        {"1942",     "1942"},
        {"1943",     "1943"},
        {"commando", "Commando"},
        {"mk",       "Mortal Kombat"},
        {"mk2",      "Mortal Kombat II"},
        {"mk3",      "Mortal Kombat 3"},
        {"umk3",     "Ultimate Mortal Kombat 3"},
        {"tekken",   "철권"},
        {"tekken2",  "철권 2"},
        {"tekken3",  "철권 3"},
    };
    return db;
}

// 표시명 반환 (없으면 대문자 romName)
inline QString getGameDisplayName(const QString& romName) {
    const auto& db = gameNamesDb();
    auto it = db.find(romName.toLower());
    return (it != db.end()) ? it.value() : romName.toUpper();
}
